/* Generated by itemis CREATE code generator. */

#include "tateti.h"
#include "tateti_required.h"

/*! \file
Implementation of the state machine 'tateti'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Idle(Tateti* handle);
static void enact_main_region_Playing(Tateti* handle);
static void enact_main_region_Check_win(Tateti* handle);
static void enact_main_region_Match_end(Tateti* handle);
static void enact_main_region_Game_over(Tateti* handle);
static void enseq_main_region_Idle_default(Tateti* handle);
static void enseq_main_region_Playing_default(Tateti* handle);
static void enseq_main_region_Check_win_default(Tateti* handle);
static void enseq_main_region_Match_end_default(Tateti* handle);
static void enseq_main_region_Game_over_default(Tateti* handle);
static void enseq_main_region_default(Tateti* handle);
static void exseq_main_region_Idle(Tateti* handle);
static void exseq_main_region_Playing(Tateti* handle);
static void exseq_main_region_Check_win(Tateti* handle);
static void exseq_main_region_Match_end(Tateti* handle);
static void exseq_main_region_Game_over(Tateti* handle);
static void exseq_main_region(Tateti* handle);
static void react_main_region__entry_Default(Tateti* handle);

/*! The reactions of state Idle. */
static sc_integer main_region_Idle_react(Tateti* handle, const sc_integer transitioned_before);

/*! The reactions of state Playing. */
static sc_integer main_region_Playing_react(Tateti* handle, const sc_integer transitioned_before);

/*! The reactions of state Check_win. */
static sc_integer main_region_Check_win_react(Tateti* handle, const sc_integer transitioned_before);

/*! The reactions of state Match_end. */
static sc_integer main_region_Match_end_react(Tateti* handle, const sc_integer transitioned_before);

/*! The reactions of state Game_over. */
static sc_integer main_region_Game_over_react(Tateti* handle, const sc_integer transitioned_before);


static void clear_in_events(Tateti* handle);

static void micro_step(Tateti* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Tateti* handle);



const sc_integer TATETI_TATETIINTERNAL_P1 = 1;
const sc_integer TATETI_TATETIINTERNAL_P2 = 2;
const sc_integer TATETI_TATETIINTERNAL_WINS = 3;



static void tateti_eventqueue_init(tateti_eventqueue * eq, tateti_event *buffer, sc_integer capacity);
static sc_integer tateti_eventqueue_size(tateti_eventqueue * eq);
static void tateti_event_init(tateti_event * ev, TatetiEventID name);
static tateti_event tateti_eventqueue_pop(tateti_eventqueue * eq);
static sc_boolean tateti_eventqueue_push(tateti_eventqueue * eq, tateti_event ev);
static sc_boolean tateti_dispatch_event(Tateti* handle, const tateti_event * event);
static tateti_event tateti_get_next_event(Tateti* handle);
static sc_boolean tateti_dispatch_next_event(Tateti* handle);
static void tateti_event_value_init(tateti_event * ev, TatetiEventID name, void * value);
static void tateti_add_value_event_to_queue(tateti_eventqueue * eq, TatetiEventID name, void * value);


void tateti_init(Tateti* handle)
{
	sc_integer i;
	
	for (i = 0; i < TATETI_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Tateti_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart tateti */
	tateti_set_current_player(handle, 1);
	tateti_set_p1_score(handle, 0);
	tateti_set_p2_score(handle, 0);
	tateti_set_winner(handle, 0);
	tateti_set_win_type(handle, 0);
	
	handle->isExecuting = bool_false;
	tateti_eventqueue_init(&handle->in_event_queue, handle->in_buffer, TATETI_IN_EVENTQUEUE_BUFFERSIZE);
}

void tateti_enter(Tateti* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart tateti */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void tateti_exit(Tateti* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart tateti */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Tateti_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void tateti_trigger_without_event(Tateti* handle) {
	run_cycle(handle);
}


sc_boolean tateti_is_active(const Tateti* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < TATETI_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Tateti_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean tateti_is_final(const Tateti* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean tateti_is_state_active(const Tateti* handle, TatetiStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Tateti_main_region_Idle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TATETI_MAIN_REGION_IDLE] == Tateti_main_region_Idle
			);
				break;
		case Tateti_main_region_Playing :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TATETI_MAIN_REGION_PLAYING] == Tateti_main_region_Playing
			);
				break;
		case Tateti_main_region_Check_win :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TATETI_MAIN_REGION_CHECK_WIN] == Tateti_main_region_Check_win
			);
				break;
		case Tateti_main_region_Match_end :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TATETI_MAIN_REGION_MATCH_END] == Tateti_main_region_Match_end
			);
				break;
		case Tateti_main_region_Game_over :
			result = (sc_boolean) (handle->stateConfVector[SCVI_TATETI_MAIN_REGION_GAME_OVER] == Tateti_main_region_Game_over
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Tateti* handle)
{
	handle->iface.key_pressed_raised = bool_false;
}

static void micro_step(Tateti* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Tateti_main_region_Idle :
		{
			main_region_Idle_react(handle,-1);
			break;
		}
		case Tateti_main_region_Playing :
		{
			main_region_Playing_react(handle,-1);
			break;
		}
		case Tateti_main_region_Check_win :
		{
			main_region_Check_win_react(handle,-1);
			break;
		}
		case Tateti_main_region_Match_end :
		{
			main_region_Match_end_react(handle,-1);
			break;
		}
		case Tateti_main_region_Game_over :
		{
			main_region_Game_over_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Tateti* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	tateti_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (tateti_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void tateti_raise_key_pressed(Tateti* handle, sc_integer value)
{
	tateti_add_value_event_to_queue(&(handle->in_event_queue), Tateti_key_pressed, &value);
	run_cycle(handle);
}



sc_integer tateti_get_current_player(const Tateti* handle)
{
	return handle->iface.current_player;
}
void tateti_set_current_player(Tateti* handle, sc_integer value)
{
	handle->iface.current_player = value;
}
sc_integer tateti_get_p1_score(const Tateti* handle)
{
	return handle->iface.p1_score;
}
void tateti_set_p1_score(Tateti* handle, sc_integer value)
{
	handle->iface.p1_score = value;
}
sc_integer tateti_get_p2_score(const Tateti* handle)
{
	return handle->iface.p2_score;
}
void tateti_set_p2_score(Tateti* handle, sc_integer value)
{
	handle->iface.p2_score = value;
}
sc_integer tateti_get_winner(const Tateti* handle)
{
	return handle->iface.winner;
}
void tateti_set_winner(Tateti* handle, sc_integer value)
{
	handle->iface.winner = value;
}
sc_integer tateti_get_win_type(const Tateti* handle)
{
	return handle->iface.win_type;
}
void tateti_set_win_type(Tateti* handle, sc_integer value)
{
	handle->iface.win_type = value;
}



/* implementations of all internal functions */

/* Entry action for state 'Idle'. */
static void enact_main_region_Idle(Tateti* handle)
{
	/* Entry action for state 'Idle'. */
	tateti_set_current_player(handle, TATETI_TATETIINTERNAL_P1);
	tateti_set_p1_score(handle, 0);
	tateti_set_p2_score(handle, 0);
	tateti_show_color_selection(handle);
}

/* Entry action for state 'Playing'. */
static void enact_main_region_Playing(Tateti* handle)
{
	/* Entry action for state 'Playing'. */
	tateti_update_display(handle,handle->iface.p1_score, handle->iface.p2_score, handle->iface.current_player);
}

/* Entry action for state 'Check_win'. */
static void enact_main_region_Check_win(Tateti* handle)
{
	/* Entry action for state 'Check_win'. */
	tateti_set_win_type(handle, tateti_check_win(handle));
}

/* Entry action for state 'Match_end'. */
static void enact_main_region_Match_end(Tateti* handle)
{
	/* Entry action for state 'Match_end'. */
	tateti_show_match_win(handle,handle->iface.win_type, handle->iface.winner);
	tateti_update_display(handle,handle->iface.p1_score, handle->iface.p2_score, handle->iface.current_player);
}

/* Entry action for state 'Game_over'. */
static void enact_main_region_Game_over(Tateti* handle)
{
	/* Entry action for state 'Game_over'. */
	tateti_show_game_win(handle,handle->iface.winner);
	tateti_update_display(handle,handle->iface.p1_score, handle->iface.p2_score, handle->iface.current_player);
}

/* 'default' enter sequence for state Idle */
static void enseq_main_region_Idle_default(Tateti* handle)
{
	/* 'default' enter sequence for state Idle */
	enact_main_region_Idle(handle);
	handle->stateConfVector[0] = Tateti_main_region_Idle;
}

/* 'default' enter sequence for state Playing */
static void enseq_main_region_Playing_default(Tateti* handle)
{
	/* 'default' enter sequence for state Playing */
	enact_main_region_Playing(handle);
	handle->stateConfVector[0] = Tateti_main_region_Playing;
}

/* 'default' enter sequence for state Check_win */
static void enseq_main_region_Check_win_default(Tateti* handle)
{
	/* 'default' enter sequence for state Check_win */
	enact_main_region_Check_win(handle);
	handle->stateConfVector[0] = Tateti_main_region_Check_win;
}

/* 'default' enter sequence for state Match_end */
static void enseq_main_region_Match_end_default(Tateti* handle)
{
	/* 'default' enter sequence for state Match_end */
	enact_main_region_Match_end(handle);
	handle->stateConfVector[0] = Tateti_main_region_Match_end;
}

/* 'default' enter sequence for state Game_over */
static void enseq_main_region_Game_over_default(Tateti* handle)
{
	/* 'default' enter sequence for state Game_over */
	enact_main_region_Game_over(handle);
	handle->stateConfVector[0] = Tateti_main_region_Game_over;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Tateti* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Idle */
static void exseq_main_region_Idle(Tateti* handle)
{
	/* Default exit sequence for state Idle */
	handle->stateConfVector[0] = Tateti_last_state;
}

/* Default exit sequence for state Playing */
static void exseq_main_region_Playing(Tateti* handle)
{
	/* Default exit sequence for state Playing */
	handle->stateConfVector[0] = Tateti_last_state;
}

/* Default exit sequence for state Check_win */
static void exseq_main_region_Check_win(Tateti* handle)
{
	/* Default exit sequence for state Check_win */
	handle->stateConfVector[0] = Tateti_last_state;
}

/* Default exit sequence for state Match_end */
static void exseq_main_region_Match_end(Tateti* handle)
{
	/* Default exit sequence for state Match_end */
	handle->stateConfVector[0] = Tateti_last_state;
}

/* Default exit sequence for state Game_over */
static void exseq_main_region_Game_over(Tateti* handle)
{
	/* Default exit sequence for state Game_over */
	handle->stateConfVector[0] = Tateti_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Tateti* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of tateti.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Tateti_main_region_Idle :
		{
			exseq_main_region_Idle(handle);
			break;
		}
		case Tateti_main_region_Playing :
		{
			exseq_main_region_Playing(handle);
			break;
		}
		case Tateti_main_region_Check_win :
		{
			exseq_main_region_Check_win(handle);
			break;
		}
		case Tateti_main_region_Match_end :
		{
			exseq_main_region_Match_end(handle);
			break;
		}
		case Tateti_main_region_Game_over :
		{
			exseq_main_region_Game_over(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Tateti* handle)
{
	/* Default react sequence for initial entry  */
	tateti_init_board(handle);
	enseq_main_region_Idle_default(handle);
}


static sc_integer main_region_Idle_react(Tateti* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Idle. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->iface.key_pressed_raised) == bool_true) && ((tateti_is_board_key(handle,handle->iface.key_pressed_value)) == bool_true))
		{ 
			exseq_main_region_Idle(handle);
			tateti_reset_board(handle);
			enseq_main_region_Playing_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->iface.key_pressed_raised) == bool_true) && ((tateti_is_color_p1_key(handle,handle->iface.key_pressed_value)) == bool_true))
			{ 
				exseq_main_region_Idle(handle);
				tateti_cycle_color_p1(handle);
				enseq_main_region_Idle_default(handle);
				transitioned_after = 0;
			}  else
			{
				if (((handle->iface.key_pressed_raised) == bool_true) && ((tateti_is_color_p2_key(handle,handle->iface.key_pressed_value)) == bool_true))
				{ 
					exseq_main_region_Idle(handle);
					tateti_cycle_color_p2(handle);
					enseq_main_region_Idle_default(handle);
					transitioned_after = 0;
				} 
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_Playing_react(Tateti* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Playing. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->iface.key_pressed_raised) == bool_true) && (((tateti_is_board_key(handle,handle->iface.key_pressed_value) == bool_true) && (tateti_is_valid_move(handle,tateti_key_to_position(handle,handle->iface.key_pressed_value)) == bool_true)) == bool_true))
		{ 
			exseq_main_region_Playing(handle);
			tateti_make_move(handle,tateti_key_to_position(handle,handle->iface.key_pressed_value), handle->iface.current_player);
			enseq_main_region_Check_win_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->iface.key_pressed_raised) == bool_true) && ((tateti_is_reset_key(handle,handle->iface.key_pressed_value)) == bool_true))
			{ 
				exseq_main_region_Playing(handle);
				enseq_main_region_Idle_default(handle);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_Check_win_react(Tateti* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Check_win. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->iface.win_type) != (0)) && ((handle->iface.current_player) == (TATETI_TATETIINTERNAL_P1)))
		{ 
			exseq_main_region_Check_win(handle);
			tateti_set_winner(handle, TATETI_TATETIINTERNAL_P1);
			handle->iface.p1_score++;
			enseq_main_region_Match_end_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->iface.win_type) != (0)) && ((handle->iface.current_player) == (TATETI_TATETIINTERNAL_P2)))
			{ 
				exseq_main_region_Check_win(handle);
				tateti_set_winner(handle, TATETI_TATETIINTERNAL_P2);
				handle->iface.p2_score++;
				enseq_main_region_Match_end_default(handle);
				transitioned_after = 0;
			}  else
			{
				if (((handle->iface.win_type) == (0)) && (tateti_check_draw(handle) == bool_true))
				{ 
					exseq_main_region_Check_win(handle);
					tateti_set_winner(handle, 0);
					enseq_main_region_Match_end_default(handle);
					transitioned_after = 0;
				}  else
				{
					if (((handle->iface.win_type) == (0)) && (tateti_check_draw(handle) == bool_false))
					{ 
						exseq_main_region_Check_win(handle);
						tateti_set_current_player(handle, ((handle->iface.current_player) == (TATETI_TATETIINTERNAL_P1)) ? TATETI_TATETIINTERNAL_P2 : TATETI_TATETIINTERNAL_P1);
						enseq_main_region_Playing_default(handle);
						transitioned_after = 0;
					} 
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_Match_end_react(Tateti* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Match_end. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->iface.p1_score) >= (TATETI_TATETIINTERNAL_WINS)) || ((handle->iface.p2_score) >= (TATETI_TATETIINTERNAL_WINS)))
		{ 
			exseq_main_region_Match_end(handle);
			enseq_main_region_Game_over_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (((handle->iface.p1_score) < (TATETI_TATETIINTERNAL_WINS)) && ((handle->iface.p2_score) < (TATETI_TATETIINTERNAL_WINS)))
			{ 
				exseq_main_region_Match_end(handle);
				tateti_reset_board(handle);
				tateti_set_current_player(handle, (((((handle->iface.p1_score + handle->iface.p2_score)) % 2)) == (0)) ? TATETI_TATETIINTERNAL_P1 : TATETI_TATETIINTERNAL_P2);
				enseq_main_region_Playing_default(handle);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer main_region_Game_over_react(Tateti* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Game_over. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (((handle->iface.key_pressed_raised) == bool_true) && ((tateti_is_reset_key(handle,handle->iface.key_pressed_value)) == bool_true))
		{ 
			exseq_main_region_Game_over(handle);
			enseq_main_region_Idle_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}




static void tateti_eventqueue_init(tateti_eventqueue * eq, tateti_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer tateti_eventqueue_size(tateti_eventqueue * eq)
{
	return eq->size;
}

static tateti_event tateti_eventqueue_pop(tateti_eventqueue * eq)
{
	tateti_event event;
	if(tateti_eventqueue_size(eq) <= 0) {
		tateti_event_init(&event, Tateti_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean tateti_eventqueue_push(tateti_eventqueue * eq, tateti_event ev)
{
	if(tateti_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void tateti_event_init(tateti_event * ev, TatetiEventID name)
{
	ev->name = name;
	ev->has_value = bool_false;
}

static sc_boolean tateti_dispatch_event(Tateti* handle, const tateti_event * event) {
	switch(event->name) {
		case Tateti_key_pressed:
		{
			handle->iface.key_pressed_raised = bool_true;
			handle->iface.key_pressed_value = event->value.Tateti_key_pressed_value;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static tateti_event tateti_get_next_event(Tateti* handle)
{
	tateti_event next_event;
	tateti_event_init(&next_event, Tateti_invalid_event);
	if(tateti_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = tateti_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean tateti_dispatch_next_event(Tateti* handle)
{
	tateti_event nextEvent;
	nextEvent = tateti_get_next_event(handle);
	return tateti_dispatch_event(handle, &nextEvent);
}

static void tateti_event_value_init(tateti_event * ev, TatetiEventID name, void * value)
{
	ev->name = name;
	ev->has_value = bool_true;
	
	switch(name)
	{
		case Tateti_key_pressed:
			ev->value.Tateti_key_pressed_value = *((sc_integer*)value);
			break;
		default:
			/* do nothing */
			break;
	}
}

static void tateti_add_value_event_to_queue(tateti_eventqueue * eq, TatetiEventID name, void * value)
{
	tateti_event event;
	tateti_event_value_init(&event, name, value);
	tateti_eventqueue_push(eq, event);
}
