/* Generated by itemis CREATE code generator. */

#ifndef TATETI_REQUIRED_H_
#define TATETI_REQUIRED_H_

#include "../src/sc_types.h"
#include "tateti.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- tateti_init_board
- tateti_reset_board
- tateti_is_valid_move
- tateti_make_move
- tateti_check_win
- tateti_check_draw
- tateti_update_display
- tateti_show_match_win
- tateti_show_game_win
- tateti_cycle_color_p1
- tateti_cycle_color_p2
- tateti_show_color_selection
- tateti_is_board_key
- tateti_is_color_p1_key
- tateti_is_color_p2_key
- tateti_is_reset_key
- tateti_key_to_position
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void tateti_init_board( Tateti* handle);
extern void tateti_reset_board( Tateti* handle);
extern sc_boolean tateti_is_valid_move( Tateti* handle, const sc_integer position);
extern void tateti_make_move( Tateti* handle, const sc_integer position, const sc_integer player);
extern sc_integer tateti_check_win( Tateti* handle);
extern sc_boolean tateti_check_draw( Tateti* handle);
extern void tateti_update_display( Tateti* handle, const sc_integer p1, const sc_integer p2, const sc_integer player);
extern void tateti_show_match_win( Tateti* handle, const sc_integer win_type, const sc_integer winner);
extern void tateti_show_game_win( Tateti* handle, const sc_integer winner);
extern void tateti_cycle_color_p1( Tateti* handle);
extern void tateti_cycle_color_p2( Tateti* handle);
extern void tateti_show_color_selection( Tateti* handle);
extern sc_boolean tateti_is_board_key( Tateti* handle, const sc_integer key);
extern sc_boolean tateti_is_color_p1_key( Tateti* handle, const sc_integer key);
extern sc_boolean tateti_is_color_p2_key( Tateti* handle, const sc_integer key);
extern sc_boolean tateti_is_reset_key( Tateti* handle, const sc_integer key);
extern sc_integer tateti_key_to_position( Tateti* handle, const sc_integer key);





#ifdef __cplusplus
}
#endif 

#endif /* TATETI_REQUIRED_H_ */
